import os
import sys
import time
import subprocess
from pathlib import Path
from openai import OpenAI
from zhipuai import ZhipuAI

# =========================================================================
//         TERMOS LT: AUTONOMOUS AGENT (SCENARIO B)
//         Features: Real File I/O, Shell Execution, Smart Project Gen
// =========================================================================

# --- CONFIGURATION ---
GROQ_API_KEY = "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"
ZHIPU_API_KEY = "42b0a4fbe60e4568ba1b74d5e8d030d6.xSVMYljtqVXmRr33"

# Agent Settings
WORKING_DIR = os.getcwd()
PROVIDER = "groq" # 'groq' or 'zhipu'

# --- STATE ---
class AgentState:
    def __init__(self):
        self.admin_mode = False
        self.hands_off = False  # If True, asks for confirmation before writing/deleting
        self.active_project = None

state = AgentState()

# --- CLIENTS ---
def get_llm_response(prompt, tools_available=False):
    try:
        if PROVIDER == "groq":
            client = OpenAI(api_key=GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")
            sys_prompt = "You are an autonomous terminal agent. Be precise."
            if state.admin_mode: sys_prompt += " You have Root privileges."
            response = client.chat.completions.create(
                model="llama3-70b-8192",
                messages=[{"role": "system", "content": sys_prompt}, {"role": "user", "content": prompt}],
                temperature=0.2
            )
            return response.choices[0].message.content
        else:
            client = ZhipuAI(api_key=ZHIPU_API_KEY)
            response = client.chat.completions.create(
                model="glm-4",
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content
    except Exception as e:
        return f"[API ERROR]: {str(e)}"

# --- ACTION TOOLS (File System & Shell) ---

def tool_create_directory(path):
    try:
        os.makedirs(path, exist_ok=True)
        return f"[SUCCESS] Directory created: {path}"
    except Exception as e:
        return f"[ERROR] {e}"

def tool_write_file(path, content):
    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        return f"[SUCCESS] File written: {path}"
    except Exception as e:
        return f"[ERROR] {e}"

def tool_execute_shell(command):
    try:
        # Security check for Admin mode
        dangerous_commands = ['rm -rf', 'mkfs', 'format', 'del /f']
        is_dangerous = any(x in command for x in dangerous_commands)
        
        if is_dangerous and not state.admin_mode:
            return "[DENIED] Dangerous command requires Admin Mode. Use '/ai enable root'."

        # Hands off confirmation
        if state.hands_off or is_dangerous:
            confirm = input(f"   >> CONFIRM EXECUTE '{command}'? [y/N]: ").lower()
            if confirm != 'y':
                return "[ABORTED] User cancelled action."

        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        output = result.stdout if result.stdout else result.stderr
        return f"[SHELL OUTPUT]\n{output}"
    except Exception as e:
        return f"[SHELL ERROR] {e}"

def tool_scan_directory():
    try:
        items = os.listdir(WORKING_DIR)
        return f"[SCAN] Current Directory: {WORKING_DIR}\n" + "\n".join(f" - {i}" for i in items)
    except Exception as e:
        return f"[ERROR] {e}"

# --- SMART BUILD LOGIC ---
def smart_build(project_type, name):
    print(f">> [AGENT] Analyzing requirements for {project_type} project: {name}...")
    time.sleep(1)
    
    # Create base folder
    tool_create_directory(name)
    os.chdir(name) # Enter the new project folder
    
    created_files = []

    if project_type == "python":
        # 1. main.py
        py_content = f"""# {name} - Auto Generated by TermOS Agent
import sys

def main():
    print("System Initialized for {name}...")

if __name__ == "__main__":
    main()
"""
        tool_write_file("main.py", py_content)
        created_files.append("main.py")

        # 2. requirements.txt
        tool_write_file("requirements.txt", "# Add dependencies here\n")
        created_files.append("requirements.txt")

        # 3. README.md
        tool_write_file("README.md", f"# {name}\nGenerated by TermOS Architect.")
        created_files.append("README.md")

    elif project_type == "web":
        # 1. index.html
        html = f"""<!DOCTYPE html>
<html>
<head><title>{name}</title></head>
<body><h1>Welcome to {name}</h1></body>
</html>"""
        tool_write_file("index.html", html)
        created_files.append("index.html")
        
        # 2. style.css
        tool_write_file("style.css", "body { font-family: sans-serif; }")
        created_files.append("style.css")

    elif project_type == "docker":
        dockerfile = """FROM python:3.9-slim
WORKDIR /app
COPY . .
CMD ["python", "main.py"]"""
        tool_write_file("Dockerfile", dockerfile)
        created_files.append("Dockerfile")

    # Return to root
    os.chdir("..")
    return f"[BUILD COMPLETE] Project '{name}' created with {len(created_files)} files."

# --- COMMAND PROCESSOR ---
def process_command(cmd):
    cmd_parts = cmd.strip().split()
    base_cmd = cmd_parts[0].lower()
    
    # 1. ADMIN & STATE COMMANDS
    if base_cmd == "/ai" and len(cmd_parts) > 1:
        if "enable" in cmd and "root" in cmd:
            state.admin_mode = True
            print(">> [SYSTEM] ROOT ACCESS GRANTED.")
        elif "disable" in cmd:
            state.admin_mode = False
            print(">> [SYSTEM] ROOT ACCESS REVOKED.")
        elif "hands" in cmd and "off" in cmd:
            state.hands_off = True
            print(">> [SYSTEM] SAFETY PROTOCOL ENGAGED (Hands Off).")
        elif "hands" in cmd and "on" in cmd:
            state.hands_off = False
            print(">> [SYSTEM] SAFETY PROTOCOL DISENGAGED.")
        return

    # 2. FILE SYSTEM COMMANDS (Autonomous Actions)
    if base_cmd == "/mkdir" and len(cmd_parts) > 1:
        print(tool_create_directory(cmd_parts[1]))
        return

    if base_cmd == "/touch" and len(cmd_parts) > 1:
        print(tool_write_file(cmd_parts[1], ""))
        return
        
    if base_cmd == "/write" and len(cmd_parts) > 2:
        # Usage: /write filename "content here"
        filename = cmd_parts[1]
        content = " ".join(cmd_parts[2:])
        print(tool_write_file(filename, content))
        return

    if base_cmd == "/exec":
        # Usage: /exec ls -la
        shell_cmd = cmd.replace("/exec", "").strip()
        print(tool_execute_shell(shell_cmd))
        return

    if base_cmd == "/scan":
        print(tool_scan_directory())
        return

    # 3. SMART BUILD COMMAND
    if base_cmd == "/build" and len(cmd_parts) > 2:
        # Usage: /build python myproject
        p_type = cmd_parts[1]
        p_name = cmd_parts[2]
        print(smart_build(p_type, p_name))
        return

    # 4. AI CHAT INTERACTION
    if base_cmd == "/ask":
        question = cmd.replace("/ask", "")
        print(f"Thinking...", end="", flush=True)
        response = get_llm_response(question)
        print("\r" + " " * 20 + "\r", end="")
        print(response)
        return

    # Default to AI chat if no command matches
    print("Thinking...", end="", flush=True)
    response = get_llm_response(cmd)
    print("\r" + " " * 20 + "\r", end="")
    print(response)

# --- MAIN LOOP ---
def main():
    print(r"""
    ========================================================================
    //         TERMOS LT: AUTONOMOUS AGENT (SCENARIO B)
    //         STATUS: ONLINE | FS ACCESS: GRANTED
    ========================================================================
    """)
    print(f"Working Directory: {WORKING_DIR}")
    print("Type '/help' for commands.\n")

    while True:
        try:
            role_color = "\033[91m" if state.admin_mode else "\033[92m"
            prompt = f"{role_color}AGENT@{os.path.basename(WORKING_DIR)}\033[0m > "
            
            user_input = input(prompt)
            
            if user_input.lower() in ['exit', 'quit']:
                print(">> Shutting down agent...")
                break
            
            if user_input == "/help":
                print("""
                -- SYSTEM COMMANDS --
                /ai enable root       : Enable Admin/Dangerous actions
                /ai hands off         : Ask confirmation before actions
                
                -- AUTONOMOUS ACTIONS --
                /scan                 : List files in current directory
                /mkdir [folder]       : Create a folder
                /touch [file]         : Create an empty file
                /write [file] "[text]": Write text to a file
                /exec [cmd]           : Run shell command (e.g., 'ls', 'git init')
                /build [type] [name]  : Smart build (types: python, web, docker)
                
                -- AI --
                /ask [question]       : Query the AI brain
                """)
                continue

            if user_input:
                process_command(user_input)

        except KeyboardInterrupt:
            print("\n>> Interrupted.")
            continue

if __name__ == "__main__":
    main()
